# Generated by Django 3.0.8 on 2020-07-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='Date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='po_no',
            field=models.CharField(default='missing', max_length=255),
        ),
    ]
