# Generated by Django 3.0.8 on 2020-07-19 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('gst_no', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Gst no does not match', regex='^([0-9]{2})([a-zA-Z]{7})([0-9]{3})$ ')])),
            ],
        ),
    ]
