# Generated by Django 3.0.8 on 2020-07-19 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='gst_no',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Gst no does not match', regex='/^([0-9]{2})([a-zA-Z]{7})([0-9]{3})$/')]),
        ),
    ]
