# Generated by Django 3.0.8 on 2020-07-19 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200719_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='gst_no',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Gst no does not match', regex='^([0-9]{2})([a-zA-Z]{7})([0-9]{3})$')]),
        ),
    ]
